config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create]
  resources :musics
  resources :favorites

  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :music

  def self.get_music(user)
    where('user_id = ?', "#{user.id}")
  end

  def self.check(music)
    where('music_id = ?', "#{music}")
  end
end

app/models/music.rb
class Music < ApplicationRecord
  has_many :favorites
  has_many :musics, through: :favorites


  def self.search(search)
    where('artist || genre ILIKE ?', "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: {message: "não pode ficar em branco"}, length: {maximum: 100, message: "deve conter no máximo 100 caracteres."},
                    format: { with: /\A[a-záàâãéèêíïóôõöúçñ\s]*+\z/i, message: "deve conter apenas letras." }

  validates :age, presence: { message: "não pode ficar em branco"}, length: {maximum: 3, message: "deve ser uma idade válida."},
                    numericality: { only_integer: true, message: "inválida."}

  validates :email, presence: { message: "não pode ficar em branco"},
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: "inválido" }

  has_many :favorites
  has_many :musics, through: :favorites


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @user = User.last
    @favorites = Favorite.get_music(@user)
  end

  def new
    @favorite = Favorite.new

    @music = Music.find(params[:music_id])

    # @user simula um current_user usado com devise ou outro tipo de autenticação
    @user = User.last

    if @user.favorites.check(@music.id).exists?
      flash[:danger] = "'#{@music.title}' já favoritada"
      redirect_to musics_path
    end
  end

  def create
    @favorite = Favorite.create(music_params)
    if @favorite.save
      flash[:success] = "Música salva em favoritos!"
      redirect_to musics_path
    else
      flash[:danger] = "Algo deu errado..."
      redirect_to new_favorite_path
    end
    Rails.logger.info "\n\n #{@favorite.inspect} \n\n"

  end

  def destroy
    @delete_fav = Favorite.find(params[:id]).destroy

    if @delete_fav.destroy
      flash[:warning] = "Música retirada dos seus favoritos."
    else
      flash[:danger] = "Não foi possível remover dos favoritos..."
    end
    redirect_to favorites_path
  end

  private
  def music_params
    params.require(:favorite).permit(:music_id, :user_id, :title, :artist, :genre)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @register = true
  end

  def create
    @user = User.create(users_params)

    if @user.save
      redirect_to musics_path
    else
        flash[:danger] = "#{@user.errors.full_messages}"
      redirect_to new_user_path
    end
  end

  # TODO: Don't accept duplicate emails

  private
  def users_params
    params.require(:user).permit(:name, :email, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="container text-center white-main-container">
  <div class="row">
    <div class="col-12">
      <h1 class="pacific-font">FavMusic!</h1>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <h5>Suas músicas favoritas, <%= @user.name %>:</h5>
    </div>
  </div>
  <table class="table mt-4">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Artista</th>
        <th scope="col">Gênero</th>
        <th scope="col">Favorito</th>
      </tr>
    </thead>
    <tbody>
      <% @favorites.each do |f| %>
      <tr>
        <td><%= f.title%></td>
        <td><%= f.artist %></td>
        <td><%= f.genre %></td>
        <td><%= link_to "Deletar", favorite_path(f.id), method: :delete ,class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row mt-3">
    <div class="col-4 offset-4">
      <%= link_to "Voltar", musics_path, class: "btn btn-light mt-5 btn-block", style: "background: rgb(232, 232, 232);"%>
    </div>
  </div>
</div>

app/views/favorites/new.html.erb
<%= form_for @favorite do |f| %>
<%= f.hidden_field :user_id, value: "#{@user.id}"%>
<%= f.hidden_field :music_id, value: "#{@music.id}"%>
<%= f.hidden_field :title, value: "#{@music.title}"%>
<%= f.hidden_field :artist, value: "#{@music.artist}"%>
<%= f.hidden_field :genre, value: "#{@music.genre}"%>


<div class="container white-container text-center" style="margin-top: 70px;">
  <div class="row">
    <div class="col-12">
      <h1 class="pacific-font">FavMusic!</h1>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <h5><%= @user.name %>, você está favoritando: </h5>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-12">
      <p><b>Título: </b><%= @music.title %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p><b>Artista: </b><%= @music.artist %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p><b>Gênero: </b><%= @music.genre %></p>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-10 offset-1">
      <%= f.submit "Favoritar", class: "btn btn-info btn-block btn-lg" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-10 offset-1">
      <%= link_to "Cancelar", musics_path, class: "btn btn-outline-secondary btn-lg btn-block"  %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_alert_login.html.erb
<div class="container alert-favs" >
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin-top: -55px;"><%= value %></div>
<% end %>
</div>

app/views/layouts/_alert_main.html.erb
<div class="container alert-favs" >
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin-top: 0px; margin-bottom: -50px;"><%= value %></div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark " style="background-color: #1ca2b8;">
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <%= link_to "FavMusic!", musics_path, class: "pacific-font navbar-brand" %>

<!-- button when screen size < 1028 -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <b><%= link_to "Favoritos", favorites_path, class: "nav-link text-white" %></b>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <b><%= link_to "Sair", root_path, class: "nav-link active" %></b>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavMusic!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: "layouts/navbar" unless @register%>
    <% if @register %>
      <%= render partial: "layouts/alert_login" %>
    <% else %>
      <%= render partial: "layouts/alert_main"%>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/musics/index.html.erb
<div class="container text-center white-main-container">
  <div class="row">
    <div class="col-12">
      <h1 class="pacific-font">FavMusic!</h1>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <h5>Procure uma música para favoritar</h5>
    </div>
  </div>
  <%= form_tag musics_path, :method => 'get' do %>

  <div class="row mt-3">
    <div class="col-6 offset-3">
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Digite o nome de um artista ou o gênero musical..."%>
    </div>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-info btn-block', type: "hidden" %>
  </div>
  <% end %>

  <table class="table mt-4">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Artista</th>
        <th scope="col">Gênero</th>
        <th scope="col">Favorito</th>
      </tr>
    </thead>
    <tbody>
      <% @musics.each do |m| %>
      <tr>
        <td><%= m.title%></td>
        <td><%= m.artist %></td>
        <td><%= m.genre %></td>
        <td><%= link_to "Favoritar", new_favorite_path(music_id: m.id) ,class: "btn btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<div class="container white-container">
  <div class="text-center">
    <div class="row">
      <div class="col-12">
        <h1 class="pacific-font">Bem-Vindo!</h1>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-12">
        <h4>Cadastre-se</h4>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-10 offset-1">
      <label for="name">Nome</label>
      <%= f.text_field :name, placeholder: "Ex.: Cooper", id: "name", class: "form-control"%>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-10 offset-1">
      <label for="email">E-mail</label>
      <%= f.text_field :email, placeholder: "Ex.: mars@endurance.com", id: "email", class: "form-control"%>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-10 offset-1">
      <label for="age">Idade</label>
      <%= f.text_field :age, placeholder: "Ex.: 60", id: "age", class: "form-control"%>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-10 offset-1">
      <%= f.submit "Cadastrar", class: "btn btn-info btn-block btn-lg" %>
    </div>
  </div>


</div>
<% end %>